server:
  port: 48081
  servlet:
    context-path: "/api-control-manager"
spring:
  application:
    name: teros-api-control-manager
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
# extra option
extra:
  env:
    teros_home: e:/teros_home